# gz topic published by the JointState plugin
- ros_topic_name: "joint_states"
  gz_topic_name: "joint_states" #Pitää matchata urdf-filessa olevaan plugariin
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model" # In future, this will be gz.msgs.Model
  direction: GZ_TO_ROS

- ros_topic_name: "fork_control"
  gz_topic_name: "fork_control"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz::msgs::Double"
  direction: ROS_TO_GZ