FROM ubuntu:20.04 AS runtime

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
   apt-get install -y --no-install-recommends mesa-utils && \
   rm -rf /var/lib/apt/lists/*

ENV LD_LIBRARY_PATH=/usr/lib/wsl/lib
CMD ["sh", "-lc", "/usr/bin/glxinfo -B | grep renderer"]