# Original template from
# https://github.com/Cionix90/docker_simulator/blob/main/compose.yaml

# Modifications for WSL2
# https://github.com/gazebosim/gz-sim/issues/2595#issuecomment-3366197792

services:
  test_robot:
    build:
      context: ..
      dockerfile: docker_files/Dockerfile.multi_build.test
      #args:
        #- BASE_IMAGE=ros
        #- BASE_TAG=jazzy-ros-base
        #- DISTRO=jazzy
        #- WORKSPACE=docker_simulation_ws
    container_name:  test_robot
    network_mode: host
    stdin_open: true
    tty: true

    environment:
      - ROS_DOMAIN_ID=0
      #- RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - RCUTILS_COLORIZED_OUTPUT=1

    volumes:
      - ./docker_simulator:/home/ros/ws