services:
  meteor_sim:
    build:
      context: ..
      dockerfile: ./docker_files/Dockerfile.monolithic
    image: meteor_sim:latest
    container_name: meteor_sim
    network_mode: host
    stdin_open: true
    tty: true
    ports:
      - "1883:1883" # MQTT
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      # No use for bash history or mounted volume for dev for now
      #  - ~/.bash_history:/home/ros/.bash_history
      #- ./docker_simulator:/home/ros/docker_simulation_ws
      
      # /dev/input is not probably needed as the simulation does not use teleop or devices
      - /dev/input:/dev/input
      - /dev/dri:/dev/dri
      # Should be automatically injected by gpus: all
      # Uncomment, if not so

      #- /dev/nvidia0:/dev/nvidia0
      #- /dev/nvidiactl:/dev/nvidiactl
      #- /dev/nvidia-modeset:/dev/nvidia-modeset
    environment:
      # Based on:
      # https://github.com/Cionix90/docker_simulator/tree/main
      QT_X11_NO_MITSHM: 1
      XAUTHORITY: /tmp/.docker.xauth
      ROS_DOMAIN_ID: 0
      RCUTILS_COLORIZED_OUTPUT: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all,graphics,display,video,utility,compute
      __NV_PRIME_RENDER_OFFLOAD: 1
      __GLX_VENDOR_LIBRARY_NAME: nvidia
      HISTFILE: /home/meteor/.bash_history
      HISTFILESIZE: 10000

      GZ_PARTITION: my_sim
      # These are needed for WSL2 to properly use the GPU and display:
      # https://github.com/microsoft/wslg/blob/main/samples%2Fcontainer%2FContainers.md#containerizing-gui-applications-with-wslg
      DISPLAY: ${DISPLAY}
      # Never use sofware rendering
      LIBGL_ALWAYS_SOFTWARE: 0
      # If fast dds is used, the shared memory optimisation must be disabled
      # https://github.com/eProsima/Fast-DDS/issues/1698#issuecomment-778039676
      # https://robotics.stackexchange.com/a/98163
      FASTRTPS_DEFAULT_PROFILES_FILE: /etc/fastdds.xml
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
    # gpus all deprecates runtime: nvidia but is effectively the same:
    # https://github.com/NVIDIA/nvidia-docker
    # https://github.com/skypilot-org/skypilot/issues/3834
    # https://docs.docker.com/compose/how-tos/gpu-support/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    

    
