# First we have the build layer

# Global args
ARG BASE_IMAGE=ros
ARG BASE_TAG=jazzy-ros-base
ARG DISTRO=jazzy

FROM osrf/ros:${DISTRO}-desktop-full AS builder
ARG DISTRO
ARG BUILD_DIR=/build_dir
WORKDIR ${BUILD_DIR}
COPY  ./src/test_pkg ./src/test_pkg

# Write the source command to the .bashrc to ensure ROS environment is set up for the user
RUN echo "source /opt/ros/${DISTRO}/setup.bash" >> ~/.bashrc

RUN apt-get update && apt-get install -y \
    python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install python dependencies for the test package
#RUN pip3 install --user --break-system-packages --no-cache-dir \
    #pydantic \
    #paho-mqtt \
    #PyYAML \
    #lark \
    #empy \
    #numpy \
    #catkin_pkg

SHELL ["/bin/bash", "-c"]

RUN source /opt/ros/${DISTRO}/setup.bash && \
    colcon build

# This is the runtime layer
FROM ${BASE_IMAGE}:${BASE_TAG}

# These have to be redeclared in the second stage to be used in this stage
# https://stackoverflow.com/questions/53681522/share-variable-in-multi-stage-dockerfile-arg-before-from-not-substituted
ARG BASE_IMAGE
ARG BASE_TAG
ARG DISTRO

ENV DEBIAN_FRONTEND=noninteractive

ARG USERNAME=ros
ARG USER_UID=1000
ARG USER_GID=${USER_UID}
ARG WORKSPACE=test_ws

# Use bash as the default shell for subsequent commands
# because sh does not understand commands like "source"
SHELL ["/bin/bash", "-c"]

# Copy the package.xml files to the runtime layer
# (to the root's home directory!)
COPY --from=builder /build_dir/src/test_pkg/package.xml ./src_meta/

RUN apt-get update && apt-get install -y \
    nano \
    python3-pip \
    sudo \
    # # Install the nav2 dependencies and other ros dependencies with rosdep
    # Depending on the base image, rosdep might already be initialized, so we ignore the error if it is already initialized
    && (rosdep init || true) \
    && rosdep update \
    && rosdep install --from-paths ./src_meta --ignore-src -r -y \
    && rm -rf ./src_meta \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

    # If the user already exists (e.g. by default in the base image), delete it and create new
RUN if id -u ${USER_UID} ; then userdel `id -un ${USER_UID}` ; fi && \
    # Create a group named after the username
    groupadd --gid ${USER_GID} ${USERNAME} && \
    # Create user with USER_ID and add it to the group created above
    # also create home directory that is named after the user
    useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME} \
    && echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}

USER ${USERNAME}

ENV HOME=/home/${USERNAME}
ENV USER=${USERNAME}

WORKDIR /home/${USERNAME}/${WORKSPACE}

# Copy the created binaries to the new user's workspace NOT ROOT's!
COPY  --from=builder /build_dir/install ./install
# For installing the dependencies with rosdep, we need the package.xml files
# Copy them directly to the workspace


# Write the source command to the .bashrc to ensure ROS environment is set up for the user
RUN echo "source /opt/ros/${DISTRO}/setup.bash" >> ~/.bashrc

# Source the ros2 overlay
RUN source /opt/ros/${DISTRO}/setup.bash

# Install python dependencies
#RUN pip3 install --user --break-system-packages --no-cache-dir \
    #pydantic \
    #paho-mqtt \
    #PyYAML \
    #lark \
    #empy \
    #numpy \
    #catkin_pkg

RUN source /opt/ros/${DISTRO}/setup.bash

# Source the overlay
RUN echo "if [ -f ~/${WORKSPACE}/install/setup.bash ]; then source ~/${WORKSPACE}/install/setup.bash; fi" >> ~/.bashrc

#ENTRYPOINT ["ros2 launch test_pkg robot_launch.py"]

# Bash used for testing
ENTRYPOINT ["/bin/bash"]