# First we have the build layer

# Global args
ARG BASE_IMAGE=ros
ARG BASE_TAG=jazzy-ros-base
ARG DISTRO=jazzy

FROM ${BASE_IMAGE}:${BASE_TAG} AS builder
ARG DISTRO
ARG BUILD_DIR=/build_dir
WORKDIR ${BUILD_DIR}
COPY  ./src/test_pkg ./src/test_pkg
COPY ./docker_files/gz_util_pkg ./src/gz_util_pkg

SHELL ["/bin/bash", "-c"]

RUN apt-get update \
    && source /opt/ros/${DISTRO}/setup.bash \
    && (rosdep init || true) \
    && rosdep update \
    && rosdep install \
        --from-paths ./src/test_pkg ./src/gz_util_pkg \
        --ignore-src -r -y \
        --skip-keys="ros_gz_sim" \
    && source /opt/ros/${DISTRO}/setup.bash \
    && colcon build \
        --merge-install \
        --cmake-args -DBUILD_TESTING=OFF \
    && mkdir -p /pkg_meta/test_pkg /pkg_meta/gz_util_pkg \
    && cp ./src/test_pkg/package.xml /pkg_meta/test_pkg/ \
    && cp ./src/gz_util_pkg/package.xml /pkg_meta/gz_util_pkg/ \
    && rm -rf build log src \
    # Apt-get clean would probably be not necessary because ubuntu
    # images do that automatically (ubuntu is base of the ros images), but we do it just in case
    # https://docs.docker.com/build/building/best-practices/#apt-get
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# This is the runtime layer
# https://www.ros.org/reps/rep-2001.html#id95
FROM ${BASE_IMAGE}:${BASE_TAG} AS runtime

# These have to be redeclared in the second stage to be used in this stage
# https://stackoverflow.com/questions/53681522/share-variable-in-multi-stage-dockerfile-arg-before-from-not-substituted
ARG BASE_IMAGE
ARG BASE_TAG
ARG DISTRO

ENV DEBIAN_FRONTEND=noninteractive

ARG USERNAME=ros
ARG USER_UID=1000
ARG USER_GID=${USER_UID}
ARG WORKSPACE=test_ws

# Use bash as the default shell for subsequent commands
# because sh does not understand commands like "source"
SHELL ["/bin/bash", "-c"]

# Copy the package.xml files to the runtime layer
# (to the root's home directory!)
# For installing the dependencies with rosdep
COPY --from=builder /pkg_meta/test_pkg/package.xml ./src_meta/test_pkg/
COPY --from=builder /pkg_meta/gz_util_pkg/package.xml ./src_meta/gz_util_pkg/

RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-${DISTRO}-rmw-cyclonedds-cpp \
    sudo \
    # Install the ros dependencies with rosdep
    # Depending on the base image, rosdep might already be initialized, so we ignore the error if it is already initialized
    && (rosdep init || true) \
    && rosdep update \
    && rosdep install --from-paths ./src_meta/gz_util_pkg ./src_meta/test_pkg --ignore-src -r -y --dependency-types exec run --skip-keys="ros_gz_sim" \
    && rm -rf ./src_meta \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# If the user already exists (e.g. by default in the base image), delete it and create new
RUN if id -u ${USER_UID} ; then userdel `id -un ${USER_UID}` ; fi && \
    # Create a group named after the username
    groupadd --gid ${USER_GID} ${USERNAME} && \
    # Create user with USER_ID and add it to the group created above
    # also create home directory that is named after the user
    useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME} \
    && echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}

USER ${USERNAME}

ENV HOME=/home/${USERNAME}
ENV USER=${USERNAME}

WORKDIR /home/${USERNAME}/${WORKSPACE}

# Copy the created binaries to the new user's workspace NOT ROOT's!
COPY  --from=builder /build_dir/install ./install

# Write the source command to the .bashrc to ensure ROS environment is set up for the user
RUN echo "source /opt/ros/${DISTRO}/setup.bash" >> ~/.bashrc

# Source the overlay
RUN source ~/.bashrc && echo "if [ -f ~/${WORKSPACE}/install/setup.bash ]; then source ~/${WORKSPACE}/install/setup.bash; fi" >> ~/.bashrc

#ENTRYPOINT ["ros2 launch test_pkg robot_launch.py"]

# Bash used for testing
ENTRYPOINT ["/bin/bash"]
#CMD ["ros2", "launch", "test_pkg", "robot_launch"]