ARG BASE_IMAGE=osrf/ros
ARG BASE_TAG=jazzy-desktop-full

FROM ${BASE_IMAGE}:${BASE_TAG}

ENV DEBIAN_FRONTEND=noninteractive
ENV GZ_VERSION=harmonic

ARG DISTRO=jazzy
ARG USERNAME=ros
ARG USER_UID=1000
ARG USER_GID=${USER_UID}
ARG WORKSPACE=docker_simulation_ws

# Only what desktop-full doesn't already have
RUN apt-get update && apt-get install -y \
    #ros-${DISTRO}-rmw-cyclonedds-cpp \
    #ros-${DISTRO}-rosbag2-storage-mcap \
    #chrony \
    mesa-utils \
    nano \
    sudo \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Ensure requested non-root user exists
RUN if ! id -u "${USERNAME}" >/dev/null 2>&1; then \
        if ! getent group "${USERNAME}" >/dev/null 2>&1; then \
            if getent group "${USER_GID}" >/dev/null 2>&1; then \
                groupadd "${USERNAME}"; \
            else \
                groupadd --gid "${USER_GID}" "${USERNAME}"; \
            fi; \
        fi; \
        if getent passwd "${USER_UID}" >/dev/null 2>&1; then \
            useradd --gid "${USERNAME}" -m -s /bin/bash "${USERNAME}"; \
        else \
            useradd --uid "${USER_UID}" --gid "${USERNAME}" -m -s /bin/bash "${USERNAME}"; \
        fi; \
    fi

# Add the user to GPU-related groups.
# Create groups named "render" and "avahi" if they don't exist, and add the user to "video", "render" and "avahi" groups.
RUN groupadd -f render && groupadd -f avahi
# Add privileges for video, render and avahi
RUN usermod -aG video,render,avahi ${USERNAME}

# Allow sudo without password (optional but common in dev containers)
RUN echo "${USERNAME} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} && \
    chmod 0440 /etc/sudoers.d/${USERNAME}

USER ${USERNAME}


ENV HOME=/home/${USERNAME}
ENV USER=${USERNAME}

WORKDIR /home/${USERNAME}/${WORKSPACE}

# Shell setup
RUN echo "source /opt/ros/${DISTRO}/setup.bash" >> ~/.bashrc && \
    echo "if [ -f ~/${WORKSPACE}/install/setup.bash ]; then source ~/${WORKSPACE}/install/setup.bash; fi" >> ~/.bashrc && \
    echo "export GZ_SIM_SYSTEM_PLUGIN_PATH=/opt/ros/${DISTRO}/lib/" >> ~/.bashrc

#ENTRYPOINT ["/ros_entrypoint.sh"]
ENTRYPOINT [""]

# Can be replaced in docker-compose
CMD ["bash", "-c", "source /opt/ros/${DISTRO}/setup.bash && gz sim empty.sdf -v 4"]
