#https://automaticaddison.com/ros-2-navigation-tuning-guide-nav2/

amcl:
  ros__parameters:
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.05
    update_min_d: 0.05
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan
    # Set initial pose from parameters instead of waiting for a service call
    # See nav_launch/bringup_launch.py
    set_initial_pose: True

bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_topic: odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
    
    # plugin_lib_names is used to add custom BT plugins to the executor (vector of strings).
    # Built-in plugins are added automatically
    # plugin_lib_names: []

    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

controller_server:
  ros__parameters:
  #Smaller rate is better for slow CPU
    controller_frequency: 5.0
    #controller_frequency: 20.0
    costmap_update_timeout: 0.30
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2 #0.5
      movement_time_allowance: 10.0
    #In theory one could swithc between the two goal checkers, for example:
    # 1. Use the general goal checker to check if the robot is moving
    # 2. If the robot is not moving, use the precise goal checker to check if the robot is at the goa
    #In practice, this could be done by computing the path, calling followPath with simple commander
    #and supplying the general_goal_checker or precise_goal_checker with goal_checker_id param
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.5 #Increase or decrease this value to change the distance to the goal
      # About 1.4 degrees of difference in orientation
      yaw_goal_tolerance: 0.3
    # DWB parameters
    FollowPath:
      #plugin: "nav2_rotation_shim_controller::RotationShimController"
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 1.2
      max_linear_accel: 2.0
      max_linear_decel: 2.0
      # THIS NEEDS TO TAKE INTO ACCOUNT THE ROBOT SIZE
      # The robot is 2.345m long, lidar is at the center of the robot, so set
      # the lookahead distance to be ~1.25 times the robot length
      use_velocity_scaled_lookahead_dist: false
      lookahead_dist: 3.0
      min_lookahead_dist: 0.5
      max_lookahead_dist: 0.9
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 0.5
      transform_tolerance: 0.1
      approach_velocity_scaling_distance: 1.5
      min_approach_linear_velocity: 0.05
      use_approach_linear_velocity_scaling: true
      max_allowed_time_to_collision: 1.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius: 0.75
      regulated_linear_scaling_min_speed: 0.25
      use_rotate_to_heading: true # !!!
      allow_reversing: false
      rotate_to_heading_min_angle: 0.5
      max_angular_accel: 1.75
      cost_scaling_dist: 0.3
      cost_scaling_gain: 1.0
      inflation_cost_scaling_factor: 3.0

      # plugin: "nav2_rotation_shim_controller::RotationShimController"
      # primary_controller: "dwb_core::DWBLocalPlanner"
      # debug_trajectory_details: True
      # # Allow robot to move in reverse
      # # See: https://robotics.stackexchange.com/questions/109841/ros2-navigation2-local-plan-does-not-avoid-obstacle
      # min_vel_x: -0.3
      # min_vel_y: -0.3
      # max_vel_x: 1.5 #change this to affect the speed of the robot
      # max_vel_y: 0.0
      # max_vel_theta: 1.0 #Increase or decrease this value to change the speed of the robot (rotation)
      # min_speed_xy: -1.0  #?
      # max_speed_xy: 1.5 #Increase or decrease this value to change the speed of the robot
      # min_speed_theta: 0.0
      # acc_lim_x: 2.0
      # acc_lim_y: 0.0
      # acc_lim_theta: 3.2
      # decel_lim_x: -2.5
      # decel_lim_y: 0.0
      # decel_lim_theta: -3.2
      # vx_samples: 20
      # vy_samples: 5
      # vtheta_samples: 20
      # sim_time: 1.5
      # linear_granularity: 0.05
      # angular_granularity: 0.025
      # transform_tolerance: 0.2
      # #Only allows the robot to rotate to the goal orientation when it is sufficiently close to the goal location.
      # #specified below
      # xy_goal_tolerance: 0.25
      # trans_stopped_velocity: 0.25
      # short_circuit_trajectory_evaluation: True
      # stateful: True
      # #https://answers.ros.org/question/365970/
      # #critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      # critics : ["RotateToGoal", "Oscillation", "ObstacleFootprintCritic", "PathAlign", "GoalAlign", "PathDist", "GoalDist"]
      # #Critics are the ones that are used to evaluate the trajectory, the scale denotes how much the score
      # # produced by the critic is scaled
      # #BaseObstacle.scale: 0.02
      # ObstacleFootprintCritic.scale: 1.0
      # PathAlign.scale: 24.0
      # PathAlign.forward_point_distance: 0.1
      # GoalAlign.scale: 35.0
      # GoalAlign.forward_point_distance: 0.1
      # PathDist.scale: 24.0
      # GoalDist.scale: 35.0
      # RotateToGoal.scale: 32.0
      # RotateToGoal.slowing_factor: 3.5
      # RotateToGoal.lookahead_time: -1.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      #These need to be changed with the size of the robot (for example when we scale the forklift)
      width: 12
      height: 12
      resolution: 0.03
      #https://docs.nav2.org/setup_guides/footprint/setup_footprint.html
      #For local costmap, the robot footprint is a rectangle
      footprint: "[[ 2.345,  0.4475 ],[ 2.345, -0.4475 ],[-0.945, -0.4475 ],[-0.945,  0.4475 ]]"
      plugins: ["voxel_layer", "inflation_layer"] #The names used below must match the ones here
      
      # obstacle_layer:
      #   plugin: "nav2_costmap_2d::ObstacleLayer"
      #   enabled: True
      #   observation_sources: scan
      #   scan:
      #     topic: /scan
      #     #Means that the raytracing does not start befor the specified distance, in case the robot itself
      #     #is in the way of the laser
      #     #Robot width is 0,895 so half of that is 0.4475
      #     raytrace_min_range: 0.4475
      #     #Obstacles close than below this distance are not considered in the costmap
      #     obstacle_min_range: 0.4475
      #     max_obstacle_height: 2.0
      #     clearing: True
      #     marking: True
      #     data_type: "LaserScan"
      
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        #https://www.robotandchisel.com/2020/09/01/navigation2/
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        publish_voxel_map: True
        scan:
          # '<robot_namespace>' keyword shall be replaced with 'namespace' where user defined.
          # It doesn't need to start with '/'
          topic: <robot_namespace>/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.4475
          #raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.4475
          #obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        #How fast the cost decays with distance from the obstacle
        #The higher the value, the faster the cost decays
        #Credit to: https://automaticaddison.com/ros-2-navigation-tuning-guide-nav2/
        cost_scaling_factor: 2.0
        # Half of the longest cross diagonal of the robot, diagonal of box (height, width, length) 2x0.895x2.29
        # See blender files for visualization
        inflation_radius: 2.4

      # static_layer:
      #   plugin: "nav2_costmap_2d::StaticLayer"
      #   map_subscribe_transient_local: True
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_link
      footprint: "[[ 2.345,  0.4475 ],[ 2.345, -0.4475 ],[-0.945, -0.4475 ],[-0.945,  0.4475 ]]"
      resolution: 0.03
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          # '<robot_namespace>' keyword shall be replaced with 'namespace' where user defined.
          # It doesn't need to start with '/'
          topic: <robot_namespace>/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.4475
          obstacle_max_range: 2.5
          obstacle_min_range: 0.4475
      
      # voxel_layer:
      #   plugin: "nav2_costmap_2d::VoxelLayer"
      #   enabled: True
      #   publish_voxel_map: False
      #   origin_z: 0.0
      #   z_resolution: 0.2
      #   z_voxels: 16
      #   max_obstacle_height: 2.0
      #   mark_threshold: 0
      #   observation_sources: scan
      #   #publish_voxel_map: True
      #   scan:
      #     # '<robot_namespace>' keyword shall be replaced with 'namespace' where user defined.
      #     # It doesn't need to start with '/'
      #     topic: <robot_namespace>/scan
      #     max_obstacle_height: 2.0
      #     clearing: True
      #     marking: True
      #     data_type: "LaserScan"
      #     raytrace_max_range: 3.0
      #     raytrace_min_range: 0.4475
      #     #raytrace_min_range: 0.0
      #     obstacle_max_range: 2.5
      #     obstacle_min_range: 0.4475
      #     #obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.0
        # Half of the longest cross diagonal of the robot, diagonal of box (height, width, length) 2x0.895x2.29
        # See blender files for visualization
        inflation_radius: 2.4
      always_send_full_costmap: True

# The yaml_filename does not need to be specified since it going to be set by defaults in launch.
# If you'd rather set it in the yaml, remove the default "map" value in the tb3_simulation_launch.py
# file & provide full path to map below. If CLI map configuration or launch default is provided, that will be used.
# map_server:
#   ros__parameters:
#     yaml_filename: ""

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    costmap_update_timeout: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      #plugin: "nav2_navfn_planner::NavfnPlanner"
      #https://docs.nav2.org/tuning/index.html#planner-plugin-selection
      plugin: "nav2_smac_planner::SmacPlannerLattice"
      allow_unknown: True

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    action_server_result_timeout: 900.0
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    #xyz-axis
    #Change these so velocity smoother does not limit speeds from the controller server (DWB planner)
    max_velocity: [2.0, 2.0, 0.75]
    min_velocity: [-0.26, 0.0, -1.0]
    max_accel: [2.0, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

collision_monitor:
  ros__parameters:
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 1.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    # Polygons represent zone around the robot for "stop", "slowdown" and "limit" action types,
    # and robot footprint for "approach" action type.
    polygons: ["FootprintApproach"]
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      
      footprint_topic: "local_costmap/published_footprint"
      time_before_collision: 1.4
      simulation_time_step: 0.1
      #Minimum amount of obstacles before the robot starts to slow down
      min_points: 6
      visualize: False
      enabled: True
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "<robot_namespace>/scan"
      min_height: 0.15
      max_height: 2.0
      enabled: True

slam_toolbox:
  ros__parameters:
    resolution: 0.03