/**/*:
  ros__parameters:
    bridge:
      mqtt2ros:
        drop:
          primitive: true
          ros_topic: drop
          ros_type: std_msgs/msg/String
        move:
          primitive: true
          ros_topic: move
          ros_type: std_msgs/msg/Float32MultiArray
        mqtt_topics:
        - robot1/move
        - robot1/drop
        - robot1/pick_up
        - robot1/ping/ros
        pick_up:
          primitive: true
          ros_topic: pick_up
          ros_type: std_msgs/msg/String
        ping/ros:
          primitive: true
          ros_topic: ping/ros
      ros2mqtt:
        /feedback:
          mqtt_topic: feedback
        /pingpong/ros:
          mqtt_topic: pingpong/ros
        ros_topics:
        - feedback
        - /pingpong/ros
    broker:
      host: localhost
      port: 1883
