# gz topic published by the JointState plugin
- ros_topic_name: "joint_states"
  gz_topic_name: "joint_states" #Pitää matchata urdf-filessa olevaan plugariin
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model" # In future, this will be gz.msgs.Model
  direction: GZ_TO_ROS

- ros_topic_name: "fork_control"
  gz_topic_name: "fork_control"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "forklift/touched"
  gz_topic_name: "cube/touched"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: GZ_TO_ROS

- ros_topic_name: "cube_pose"
  gz_topic_name: "/model/cube/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
