robots:
  - name: drone_133
    package: "drone_cpp"
    type: "drone"
    starting_position: [0.0, 0, 0]
    starting_orientation: [0, 0, 0]
    gz_bridge_config: "drone_ros_gz_bridge.yaml"
    nav2_config: "drone_nav2_config.yaml"
    launch_file: "drone_launch.py"
  # - name: forklift_1
  #   package: "forklift_controller"
  #   type: "forklift"
  #   start_position: [0, 0, 0]
  #   # roll, pitch, yaw in radians
  #   start_orientation: [0, 0, 0]
  #   gz_bridge_config: "forklift_ros_gz_bridge.yaml"
  #   nav2_config: "forklift_nav2_config.yaml"
  #   launch_file: "forklift_simulation.launch.py"