- service_name: "/world/empty/create"
  gz_req_type_name: "gz.msgs.Pose"
  gz_res_type_name: "gz.msgs.Boolean"
  ros_type_name: "ros_gz_interfaces/srv/SpawnEntity"
  direction: BIDIRECTIONAL

expand_gz_topic_names: true
use_sim_time: true
