<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>forklift_controller</name>
  <version>0.0.0</version>
  <description>Package for controlling a forklift simulation through AI prompt</description>
  <maintainer email="elmeri.pohjois-koivisto@tuni.fi">Elmeri Pohjois-Koivisto</maintainer>
  <license>TODO: License declaration</license>
  
  <!--Not needed if not using ros control?-->
  <!--
    <exec_depend>controller_manager</exec_depend>
-->
  <exec_depend>ros_gz</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <!-- <exec_depend>ros_gz_image</exec_depend> -->
  <!-- <exec_depend>trajectory_msgs</exec_depend> -->
  <exec_depend>xacro</exec_depend>
  <exec_depend>movement_interface</exec_depend>
  <exec_depend>mqtt_client</exec_depend>
  <depend>rclpy</depend>
  <depend>joint_state_publisher</depend>
   <!--Useful for experimentation-->
  <depend>joint_state_publisher_gui</depend>
  <depend>robot_state_publisher</depend>
  <depend>tf_transformations</depend>
  <depend>rviz2</depend>


  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>


  <export>
    <build_type>ament_python</build_type>
    <gazebo_ros gazebo_model_path="${prefix}/.."/>
  </export>
</package>
